-- Function to insert OHADA chart of accounts for a company
CREATE OR REPLACE FUNCTION insert_ohada_chart(p_company_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Insert all OHADA accounts
  INSERT INTO accounts (company_id, code, name, type, reconcilable) VALUES
  (p_company_id, '10', 'CAPITAUX PROPRES ET RESSOURCES ASSIMILEES', 'equity', false),
  (p_company_id, '101000', 'Capital social', 'equity', false),
  (p_company_id, '106000', 'Réserves', 'equity', false),
  (p_company_id, '110000', 'Report à nouveau', 'equity', false),
  (p_company_id, '120000', 'Résultat de l''exercice', 'equity', false),
  (p_company_id, '13', 'EMPRUNTS ET DETTES ASSIMILEES', 'liability', false),
  (p_company_id, '161000', 'Emprunts et dettes auprès des établissements de crédit', 'liability', false),
  (p_company_id, '164000', 'Emprunts et dettes auprès de l''Etat', 'liability', false),
  (p_company_id, '165000', 'Dépôts et cautionnements reçus', 'liability', false),
  (p_company_id, '20', 'CHARGES IMMOBILISEES', 'asset', false),
  (p_company_id, '201000', 'Frais de développement', 'asset', false),
  (p_company_id, '206000', 'Logiciels et sites internet', 'asset', false),
  (p_company_id, '21', 'IMMOBILISATIONS INCORPORELLES', 'asset', false),
  (p_company_id, '211000', 'Frais de recherche et de développement', 'asset', false),
  (p_company_id, '213000', 'Brevets licences logiciels', 'asset', false),
  (p_company_id, '215000', 'Fonds commercial', 'asset', false),
  (p_company_id, '22', 'TERRAINS', 'asset', false),
  (p_company_id, '221000', 'Terrains nus', 'asset', false),
  (p_company_id, '222000', 'Terrains aménagés', 'asset', false),
  (p_company_id, '23', 'BATIMENTS INSTALLATIONS TECHNIQUES ET AGENCEMENTS', 'asset', false),
  (p_company_id, '231000', 'Bâtiments industriels', 'asset', false),
  (p_company_id, '232000', 'Bâtiments administratifs et commerciaux', 'asset', false),
  (p_company_id, '233000', 'Bâtiments d''habitation', 'asset', false),
  (p_company_id, '237000', 'Agencements et aménagements de bureaux', 'asset', false),
  (p_company_id, '24', 'MATERIEL', 'asset', false),
  (p_company_id, '241000', 'Matériel et outillage industriel et commercial', 'asset', false),
  (p_company_id, '244000', 'Matériel de bureau', 'asset', false),
  (p_company_id, '245000', 'Matériel de transport', 'asset', false),
  (p_company_id, '246000', 'Matériel informatique', 'asset', false),
  (p_company_id, '40', 'FOURNISSEURS ET COMPTES RATTACHES', 'liability', false),
  (p_company_id, '401000', 'Fournisseurs dettes en compte', 'liability', true),
  (p_company_id, '408000', 'Fournisseurs factures non parvenues', 'liability', false),
  (p_company_id, '409000', 'Fournisseurs débiteurs avances et acomptes versés', 'liability', true),
  (p_company_id, '41', 'CLIENTS ET COMPTES RATTACHES', 'asset', false),
  (p_company_id, '411000', 'Clients', 'asset', true),
  (p_company_id, '413000', 'Clients effets à recevoir', 'asset', true),
  (p_company_id, '416000', 'Créances clients douteuses', 'asset', true),
  (p_company_id, '418000', 'Clients produits à recevoir', 'asset', false),
  (p_company_id, '419000', 'Clients créditeurs avances et acomptes reçus', 'asset', true),
  (p_company_id, '42', 'PERSONNEL ET ORGANISMES SOCIAUX', 'liability', false),
  (p_company_id, '421000', 'Personnel avances et acomptes', 'liability', true),
  (p_company_id, '422000', 'Personnel rémunérations dues', 'liability', false),
  (p_company_id, '423000', 'Personnel oppositions sur salaires', 'liability', false),
  (p_company_id, '425000', 'Personnel provisions pour congés à payer', 'liability', false),
  (p_company_id, '427000', 'Personnel charges à payer', 'liability', false),
  (p_company_id, '431000', 'Sécurité sociale', 'liability', false),
  (p_company_id, '432000', 'Autres organismes sociaux', 'liability', false),
  (p_company_id, '44', 'ETAT ET COLLECTIVITES PUBLIQUES', 'liability', false),
  (p_company_id, '441000', 'Etat subventions à recevoir', 'asset', false),
  (p_company_id, '442000', 'Etat impôts et taxes recouvrables', 'asset', false),
  (p_company_id, '443000', 'Operations particulieres avec l''Etat', 'liability', false),
  (p_company_id, '445000', 'Etat TVA facturée', 'liability', false),
  (p_company_id, '445710', 'TVA collectée', 'liability', false),
  (p_company_id, '445800', 'TVA à régulariser', 'liability', false),
  (p_company_id, '446000', 'Etat autres impôts et taxes', 'liability', false),
  (p_company_id, '447000', 'Etat impôts retenus à la source', 'liability', false),
  (p_company_id, '448000', 'Etat charges à payer', 'liability', false),
  (p_company_id, '45', 'ORGANISMES INTERNATIONAUX', 'asset', false),
  (p_company_id, '451000', 'Organismes internationaux opérations particulières', 'asset', false),
  (p_company_id, '458000', 'Organismes internationaux charges à payer et produits à recevoir', 'asset', false),
  (p_company_id, '46', 'ASSOCIES ET GROUPE', 'liability', false),
  (p_company_id, '461000', 'Associés capital souscrit appelé non versé', 'asset', true),
  (p_company_id, '465000', 'Associés comptes courants', 'liability', true),
  (p_company_id, '467000', 'Actionnaires capital souscrit non appelé', 'equity', false),
  (p_company_id, '47', 'DEBITEURS ET CREDITEURS DIVERS', 'asset', false),
  (p_company_id, '471000', 'Débiteurs divers', 'asset', true),
  (p_company_id, '472000', 'Créditeurs divers', 'liability', true),
  (p_company_id, '475000', 'Créances sur cessions d''immobilisations', 'asset', true),
  (p_company_id, '476000', 'Dettes sur acquisitions d''immobilisations', 'liability', true),
  (p_company_id, '50', 'TITRES DE PLACEMENT', 'asset', false),
  (p_company_id, '501000', 'Titres du Trésor et bons de caisse à court terme', 'asset', false),
  (p_company_id, '502000', 'Actions', 'asset', false),
  (p_company_id, '506000', 'Obligations', 'asset', false),
  (p_company_id, '51', 'BANQUES ETABLISSEMENTS FINANCIERS ET ASSIMILES', 'asset', false),
  (p_company_id, '511000', 'Valeurs à l''encaissement', 'asset', false),
  (p_company_id, '512000', 'Banques', 'asset', true),
  (p_company_id, '514000', 'Chèques postaux', 'asset', true),
  (p_company_id, '52', 'INSTRUMENTS DE TRESORERIE', 'asset', false),
  (p_company_id, '521000', 'Titres de placement à court terme', 'asset', false),
  (p_company_id, '53', 'CAISSE', 'asset', false),
  (p_company_id, '571000', 'Caisse siège social', 'asset', true),
  (p_company_id, '572000', 'Caisse succursale', 'asset', true),
  (p_company_id, '60', 'ACHATS ET VARIATIONS DE STOCKS', 'expense', false),
  (p_company_id, '601000', 'Achats de marchandises', 'expense', false),
  (p_company_id, '602000', 'Achats de matières premières et fournitures liées', 'expense', false),
  (p_company_id, '604000', 'Achats stockés de matières et fournitures consommables', 'expense', false),
  (p_company_id, '605000', 'Autres achats', 'expense', false),
  (p_company_id, '608000', 'Achats d''emballages', 'expense', false),
  (p_company_id, '61', 'TRANSPORTS', 'expense', false),
  (p_company_id, '611000', 'Transports sur ventes', 'expense', false),
  (p_company_id, '612000', 'Transports sur achats', 'expense', false),
  (p_company_id, '613000', 'Transports pour le compte de tiers', 'expense', false),
  (p_company_id, '614000', 'Transports du personnel', 'expense', false),
  (p_company_id, '618000', 'Autres frais de transport', 'expense', false),
  (p_company_id, '62', 'SERVICES EXTERIEURS A', 'expense', false),
  (p_company_id, '621000', 'Sous-traitance générale', 'expense', false),
  (p_company_id, '622000', 'Locations et charges locatives', 'expense', false),
  (p_company_id, '623000', 'Redevances de crédit-bail', 'expense', false),
  (p_company_id, '624000', 'Entretien réparations et maintenance', 'expense', false),
  (p_company_id, '625000', 'Primes d''assurances', 'expense', false),
  (p_company_id, '626000', 'Etudes recherches et documentation', 'expense', false),
  (p_company_id, '627000', 'Publicité publications et relations publiques', 'expense', false),
  (p_company_id, '628000', 'Frais de télécommunications', 'expense', false),
  (p_company_id, '63', 'SERVICES EXTERIEURS B', 'expense', false),
  (p_company_id, '631000', 'Frais bancaires', 'expense', false),
  (p_company_id, '632000', 'Rémunérations d''intermédiaires et de conseils', 'expense', false),
  (p_company_id, '633000', 'Frais de formation du personnel', 'expense', false),
  (p_company_id, '634000', 'Réceptions', 'expense', false),
  (p_company_id, '635000', 'Missions et déplacements', 'expense', false),
  (p_company_id, '637000', 'Redevances pour brevets licences logiciels', 'expense', false),
  (p_company_id, '64', 'IMPOTS ET TAXES', 'expense', false),
  (p_company_id, '641000', 'Impôts et taxes directs', 'expense', false),
  (p_company_id, '645000', 'Autres impôts et taxes', 'expense', false),
  (p_company_id, '646000', 'Droits d''enregistrement', 'expense', false),
  (p_company_id, '647000', 'Pénalités et amendes fiscales', 'expense', false),
  (p_company_id, '65', 'AUTRES CHARGES', 'expense', false),
  (p_company_id, '651000', 'Pertes sur créances clients', 'expense', false),
  (p_company_id, '658000', 'Charges diverses', 'expense', false),
  (p_company_id, '66', 'CHARGES DE PERSONNEL', 'expense', false),
  (p_company_id, '661000', 'Appointements salaires et commissions', 'expense', false),
  (p_company_id, '662000', 'Primes et gratifications', 'expense', false),
  (p_company_id, '663000', 'Congés payés', 'expense', false),
  (p_company_id, '664000', 'Charges sociales', 'expense', false),
  (p_company_id, '665000', 'Autres charges sociales', 'expense', false),
  (p_company_id, '67', 'FRAIS FINANCIERS ET CHARGES ASSIMILEES', 'expense', false),
  (p_company_id, '671000', 'Intérêts des emprunts', 'expense', false),
  (p_company_id, '672000', 'Intérêts dans loyers de crédit-bail', 'expense', false),
  (p_company_id, '673000', 'Escomptes accordés', 'expense', false),
  (p_company_id, '674000', 'Autres frais financiers', 'expense', false),
  (p_company_id, '676000', 'Pertes de change', 'expense', false),
  (p_company_id, '677000', 'Charges sur cession de titres de placement', 'expense', false),
  (p_company_id, '70', 'VENTES', 'income', false),
  (p_company_id, '701000', 'Ventes de marchandises', 'income', false),
  (p_company_id, '702000', 'Ventes de produits finis', 'income', false),
  (p_company_id, '703000', 'Ventes de produits intermédiaires', 'income', false),
  (p_company_id, '704000', 'Ventes de produits résiduels', 'income', false),
  (p_company_id, '706000', 'Services vendus', 'income', false),
  (p_company_id, '707000', 'Produits de négoce', 'income', false),
  (p_company_id, '71', 'SUBVENTIONS D''EXPLOITATION', 'income', false),
  (p_company_id, '711000', 'Subventions d''équilibre', 'income', false),
  (p_company_id, '712000', 'Subventions compensatrices', 'income', false),
  (p_company_id, '718000', 'Autres subventions d''exploitation', 'income', false),
  (p_company_id, '72', 'PRODUCTION IMMOBILISEE', 'income', false),
  (p_company_id, '721000', 'Immobilisations incorporelles', 'income', false),
  (p_company_id, '722000', 'Immobilisations corporelles', 'income', false),
  (p_company_id, '73', 'VARIATIONS DES STOCKS DE BIENS ET DE SERVICES PRODUITS', 'income', false),
  (p_company_id, '734000', 'Variations des stocks de produits en cours', 'income', false),
  (p_company_id, '735000', 'Variations des stocks de services en cours', 'income', false),
  (p_company_id, '74', 'PRESTATIONS FOURNIES', 'income', false),
  (p_company_id, '741000', 'Travaux', 'income', false),
  (p_company_id, '742000', 'Etudes', 'income', false),
  (p_company_id, '743000', 'Prestations de services', 'income', false),
  (p_company_id, '75', 'AUTRES PRODUITS', 'income', false),
  (p_company_id, '751000', 'Redevances pour brevets licences', 'income', false),
  (p_company_id, '752000', 'Revenus des immeubles non affectés aux activités professionnelles', 'income', false),
  (p_company_id, '753000', 'Jetons de présence', 'income', false),
  (p_company_id, '754000', 'Ristournes perçues des coopératives', 'income', false),
  (p_company_id, '758000', 'Produits divers', 'income', false),
  (p_company_id, '77', 'REVENUS FINANCIERS ET PRODUITS ASSIMILES', 'income', false),
  (p_company_id, '771000', 'Intérêts de prêts', 'income', false),
  (p_company_id, '772000', 'Revenus de participations', 'income', false),
  (p_company_id, '773000', 'Escomptes obtenus', 'income', false),
  (p_company_id, '776000', 'Gains de change', 'income', false),
  (p_company_id, '777000', 'Produits de cession de titres de placement', 'income', false);
  
  RAISE NOTICE 'Plan comptable OHADA inséré pour company_id: %', p_company_id;
END;
$$;

-- Trigger to automatically insert OHADA chart when a new company is created
CREATE OR REPLACE FUNCTION auto_insert_ohada_chart()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Insert OHADA chart for the new company
  PERFORM insert_ohada_chart(NEW.id);
  RETURN NEW;
END;
$$;

-- Create trigger on companies table
DROP TRIGGER IF EXISTS trigger_auto_insert_ohada_chart ON companies;
CREATE TRIGGER trigger_auto_insert_ohada_chart
  AFTER INSERT ON companies
  FOR EACH ROW
  EXECUTE FUNCTION auto_insert_ohada_chart();